version: "3.8"
services:
  frontend:
    container_name: nextjs-frontend
    build: .
    restart: always
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:10050/api
      - NODE_ENV=production
    ports:
      - "10030:3000"
    networks:
      - my-network

networks:
  my-network:
