version: "3.8"

services:
  db:
    container_name: postgres_db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - localnetwork

networks:
  localnetwork:
    driver: bridge

volumes:
  postgres_data:
